fieldLayouts:
  c82abeab-6fb3-4a02-9057-622aee0fc85b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 95981f25-0b70-4493-ac73-8b35763c9cc1 # How Can We Partner Title
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9d395b8d-3002-4765-9a2b-45acea5d761d # How Can We Partner Subtitle
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e7a2455c-7aa3-4cc4-ab7d-244c210567f8 # Number One
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9d865bb3-3423-480b-90f2-9b6e0709a24d # Step One Heading
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c028f2c9-1328-4db9-8982-5c2cdd412695 # Programme List
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 20dcde3b-f1f4-4244-80ed-5e6b92e80af5 # Number Two
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5475acc4-915c-4f9e-8d48-add166fb9b81 # Step Two Heading
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c26c64e2-5c2e-4e97-a28d-b91c7bc182b3 # number Two Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 21f106b8-83b2-4648-9e70-94adc36fab96 # FS List
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6a2f84be-0aa8-436d-9647-8716eb634c37 # How can we partner Image
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e0ba8e8e-433f-412c-ba85-989fd3c1de95 # Number Three
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f50e3fdf-4d4a-4023-8108-532bc6d15e7a # Number Three Title
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 538b9dfc-eb73-4e50-8c2b-835f23ed08f6 # Number Three Subtitle
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ee614a99-88a5-404c-837b-345aa6e9a425 # Number Four
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1711f46b-9498-472d-a284-fdbf153b8ebf # Funders Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d37ac34e-151f-458a-b6f7-337227fa23c4 # Number Four Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bd76b64f-5737-455e-9063-f9d5fae094d3 # Number Four Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f4ea8fc1-113a-47f3-bfa4-e207d5756f53 # Further Discount
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: howCanWePartner
hasTitleField: true
name: '8. How Can We Partner'
section: 4b2794b3-5803-43bf-957c-100528311028 # 8. How Can We Partner
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
