fieldLayouts:
  7b4ac83b-438a-4f9d-a68c-530877abbf41:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 6b01ab0f-5e1e-459b-aa6a-951def457885 # Title Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9d1fb737-435c-4b0e-978b-ef8951ee24e7 # Subtitle Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7178d9a4-c778-43ea-9e73-d699d694779e # Secondary Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 42bc02db-d062-47ff-90fb-fa5e8fa1053f # Reach Stats
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: reachAndImpact
hasTitleField: false
name: '4. Reach and Impact Band'
section: 919847da-318b-45ec-bed8-97615299d97a # 4. Reach and Impact Band
sortOrder: 1
titleFormat: '4. Reach and Impact Band'
titleTranslationKeyFormat: null
titleTranslationMethod: site
